sampler:
  name: sgld
  sgld:
    # Increased steps to reach ~10k FGEs (781250 steps * (256/20000) = 10000 FGEs)
    steps: 781250
    warmup: 50000
    batch_size: 256
    step_size: 0.000001
    dtype: float32
    precond: none
    beta1: 0.9
    beta2: 0.999
    eps: 0.00000001
    bias_correction: true
    # Increased thinning due to large step count
    eval_every: 100