[project]
name = "llc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "arviz~=0.22.0",
    "blackjax~=1.2.5",
    "marimo>=0.15.2",
    "optax>=0.2.5",
    "scipy>=1.11",
    "tqdm>=4.67.1",
]

[project.scripts]
llc = "llc.cli:main"

[project.optional-dependencies]
# SLURM backend
slurm = ["submitit>=1.5"]        # Python 3.8+ and SLURM-friendly toolbox
# Modal backend
modal = ["modal>=0.64"]          # Modal's official SDK (Py 3.9–3.13)
cpu = ["jax>=0.4.28"]            # CPU-only JAX
cuda12 = ["jax[cuda12_local]>=0.4.28"]  # CUDA 12 wheels (see JAX docs)
