sampler:
  name: sgld
  sgld:
    steps: 10000
    warmup: 2000
    batch_size: 64
    step_size: 1e-6
    dtype: float32
    precond: none
    beta1: 0.9
    beta2: 0.999
    eps: 1e-8
    bias_correction: true