# Base teacher configuration
depth: 3
widths: null          # optional; if null we infer
activation: relu
dropout_rate: 0.1
# optional size drivers (choose at most one; both null is allowed -> fallback):
target_params: 100
hidden: null