# @package _global_.sampler
chains: 4

sgld:
  steps: 16000
  warmup: 1000
  batch_size: 256
  step_size: 0.000001
  dtype: float32
  precond: none
  beta1: 0.9
  beta2: 0.999
  eps: 0.00000001
  bias_correction: true

hmc:
  draws: 5000
  warmup: 1000
  num_integration_steps: 10
  step_size: 0.01
  dtype: float64
  adapt_step_size: true
  target_acceptance: 0.8

mclmc:
  draws: 8000
  L: 1.0
  step_size: 0.1
  dtype: float64
  integrator: isokinetic_mclachlan