# @package _global_.sampler
# Quick test configuration
chains: 2

sgld:
  steps: 100
  warmup: 20
  batch_size: 32
  step_size: 0.000001
  dtype: float32
  precond: none
  beta1: 0.9
  beta2: 0.999
  eps: 0.00000001
  bias_correction: true

hmc:
  draws: 50
  warmup: 20
  num_integration_steps: 5
  step_size: 0.01
  dtype: float64
  adapt_step_size: true
  target_acceptance: 0.8

mclmc:
  draws: 80
  L: 1.0
  step_size: 0.1
  dtype: float64
  integrator: isokinetic_mclachlan