# Main configuration
defaults:
  - model: base
  - data: base
  - sampler: base
  - _self_

target: mlp
seed: 42
use_tqdm: true
progress_update_every: 50
profile_adaptation: true

teacher:
  depth: null
  widths: null
  activation: null
  dropout_rate: 0.0

training:
  optimizer: adam
  learning_rate: 0.001
  erm_steps: 5000
  early_stop_tol: 0.000001

posterior:
  loss: mse
  beta_mode: "1_over_log_n"
  beta0: 1.0
  prior_radius: null
  gamma: 1.0
  prior_center: null

output:
  save_plots: true
  show_plots: false

samplers_to_run: [sgld, sgld_basic, hmc, mclmc]